# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

version: 2

config_android: &config_android
  docker:
    - image: circleci/android:api-28-alpha
  parallelism: 1
  resource_class: xlarge
  working_directory: ~/circlci
  environment:
    GRADLE_OPTS: "-Xmx6400m -Dorg.gradle.daemon=false"
    JVM_OPTS: "-Xmx6400m"
    TERM: dumb

gen_cache_key: &gen_cache_key
  run:
    name: Generate cache key
    command: |
      ./checksum.sh /tmp/checksum.txt
restore_cache: &restore_cache
  restore_cache:
    key: gradle-{{ checksum "/tmp/checksum.txt" }}

save_cache: &save_cache
  save_cache:
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
    key: gradle-{{ checksum "/tmp/checksum.txt" }}


jobs:

  config_cache:
    <<: *config_android
    steps:
      - checkout
      - <<: *gen_cache_key
      - <<: *restore_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build Project
          command: ./gradlew assembleDebug
      - <<: *save_cache

workflows:
  version: 2
  check:
    jobs:
      - config_cache:
          filters:
            branches:
              ignore:
                - master
                - /release*/