package com.mytv.series.base.providers

import androidx.annotation.ArrayRes
import androidx.annotation.ColorInt
import androidx.annotation.ColorRes
import androidx.annotation.StringRes

/**
 * This class provide the resources without a context reference
 */
interface ResourceProvider {

    /**
     * Returns a localized string from the application's package's
     * default string table.
     *
     * @param id Resource id for the string
     * @return The string data associated with the resource, stripped of styled
     *         text information.
     */
    fun getString(@StringRes id: Int): String

    /**
     * Returns a localized formatted string from the application's package's
     * default string table, substituting the format arguments as defined in
     * {@link java.util.Formatter} and {@link java.lang.String#format}.
     *
     * @param id Resource id for the format string
     * @param args The format arguments that will be used for
     *                   substitution.
     * @return The string data associated with the resource, formatted and
     *         stripped of styled text information.
     */
    fun getString(@StringRes id: Int, vararg args: Any?): String

    /**
     * Return the string array associated with a particular resource ID.
     *
     * @param id The desired resource identifier, as generated by the aapt
     *           tool. This integer encodes the package, type, and resource
     *           entry. The value 0 is an invalid identifier.
     *
     * @return The string array associated with the resource.
     */
    fun getStringArray(@ArrayRes id: Int): Array<String>

    /**
     * Returns a color associated with a particular resource ID
     * <p>
     * Starting in {@link android.os.Build.VERSION_CODES#M}, the returned
     * color will be styled for the specified Context's theme.
     *
     * @param id The desired resource identifier, as generated by the aapt
     *           tool. This integer encodes the package, type, and resource
     *           entry. The value 0 is an invalid identifier.
     * @return A single color value in the form 0xAARRGGBB.
     * @throws android.content.res.Resources.NotFoundException if the given ID
     *         does not exist.
     */
    @ColorInt
    fun getColor(@ColorRes id: Int) : Int

}